package com.manning.bippo.service.rets.pojo;

import java.lang.reflect.Field;

public class RetsResponse
{
    public String AccessibilityFeatures;
    public String AccessoryUnitType;
    public String AccessoryUnitYN;
    public String AcresBottomLand;
    public String AcresCultivated;
    public String AcresIrrigated;
    public String AcresPasture;
    public String ActiveContinueToShowDate;
    public String ActiveKickOutDate;
    public String ActiveOpenHouseCount;
    public String ActiveOptionContractDate;
    public String AerialPhotoAvailableYN;
    public String AGExemptionYN;
    public String AppliancesYN;
    public String ApplicationFeeYN;
    public String AppointmentCall;
    public String AppointmentPhone;
    public String AppointmentPhoneExt;
    public String AppraiserName;
    public String ArchitecturalStyle;
    public String AssociationFee;
    public String AssociationFeeFrequency;
    public String AssociationFeeIncludes;
    public String AssociationType;
    public String AverageMonthlyLease;
    public String BackOnMarketDate;
    public String Barn1Length;
    public String Barn1Width;
    public String Barn2Length;
    public String Barn2Width;
    public String Barn3Length;
    public String Barn3Width;
    public String BarnInformation;
    public String BathsFull;
    public String BathsHalf;
    public String BathsTotal;
    public String BedroomBathroomFeatures;
    public String BedsTotal;
    public String Block;
    public String BuildingAreaSource;
    public String BuildingNumber;
    public String BuildingUse;
    public String BusinessName;
    public String BuyersAgencyCommission;
    public String CancelledDate;
    public String CapitalizationRate;
    public String CDOM;
    public String CeilingHeight;
    public String City;
    public String CloseDate;
    public String ClosePrice;
    public String CoListAgent_MUI;
    public String CoListAgentDirectWorkPhone;
    public String CoListAgentEmail;
    public String CoListAgentFullName;
    public String CoListAgentMLSID;
    public String CoListOffice_MUI;
    public String CoListOfficeMLSID;
    public String CoListOfficeName;
    public String CoListOfficePhone;
    public String CommercialFeatures;
    public String CommunityFeatures;
    public String CompensationPaid;
    public String ComplexName;
    public String ConstructionMaterials;
    public String ConstructionMaterialsWalls;
    public String ContingencyInfo;
    public String CoSellingAgent_MUI;
    public String CoSellingAgentDirectWorkPhone;
    public String CoSellingAgentEmail;
    public String CoSellingAgentFullName;
    public String CoSellingAgentMLSID;
    public String CoSellingOffice_MUI;
    public String CoSellingOfficeMLSID;
    public String CoSellingOfficeName;
    public String CoSellingOfficePhone;
    public String CountyOrParish;
    public String CropRetireProgramYN;
    public String Crops;
    public String DateAvailable;
    public String DepositAmount;
    public String DepositPet;
    public String Development;
    public String Directions;
    public String Documents;
    public String DOM;
    public String Easements;
    public String ElementarySchoolName;
    public String EnergySavingFeatures;
    public String Equity;
    public String Exclusions;
    public String ExpirationDateOption;
    public String ExteriorBuildings;
    public String ExteriorFeatures;
    public String FarmRanchFeatures;
    public String FencedYardYN;
    public String Fencing;
    public String FHA_VA_ApprovedComplexNumber;
    public String FinancingApproved;
    public String FinancingProposed;
    public String FireplaceFeatures;
    public String FireplacesTotal;
    public String Flooring;
    public String FloorLocationNumber;
    public String FoundationDetails;
    public String FreightDoors;
    public String FrontageFeet;
    public String FurnishedYN;
    public String GarageLength;
    public String GarageWidth;
    public String GreenBuildingCertification;
    public String GreenEnergyEfficient;
    public String GrossAnnualExpenses;
    public String GrossAnnualIncome;
    public String GrossIncomeMultiplier;
    public String HandicapYN;
    public String Heating;
    public String HighSchoolName;
    public String HOAManagementCompany;
    public String HOAManagementCompanyPhone;
    public String Inclusions;
    public String IncomeExpenseSource;
    public String InsuranceExpense;
    public String InteriorFeatures;
    public String IntermediateSchoolName;
    public String InternetExposure;
    public String JuniorHighSchoolName;
    public String KeyboxNumber;
    public String KeyBoxType;
    public String LakeName;
    public String LandLeasedYN;
    public String LastListPrice;
    public String LastStatus;
    public String Latitude;
    public String LeaseConditions;
    public String LeasedDate;
    public String LeaseExpirationDate;
    public String LeaseRateMax;
    public String LeaseRateMin;
    public String LeaseTerm;
    public String LeaseTerms;
    public String LeaseType;
    public String LenderName;
    public String LesseePays;
    public String ListAgent_MUI;
    public String ListAgentDirectWorkPhone;
    public String ListAgentEmail;
    public String ListAgentFullName;
    public String ListAgentMLSID;
    public String ListingAgreement;
    public String ListingContractDate;
    public String ListingFinancing;
    public String ListingFinancing2;
    public String ListOffice_MUI;
    public String ListOfficeMLSID;
    public String ListOfficeName;
    public String ListOfficePhone;
    public String ListPrice;
    public String ListPriceLow;
    public String Loan1Amount;
    public String Loan1InterestRate;
    public String Loan1Years;
    public String Loan2Amount;
    public String Loan2InterestRate;
    public String Loan2Years;
    public String LoanBalance;
    public String LoanInterestRate;
    public String LoanPayment;
    public String LoanPaymentType;
    public String LoanType;
    public String Longitude;
    public String LotFeatures;
    public String LotNumber;
    public String LotSize;
    public String LotSizeArea;
    public String LotSizeAreaSQFT;
    public String LotSizeDimensions;
    public String LotSizeSource;
    public String LotSizeUnits;
    public String LotsSoldPackage;
    public String LotsSoldSeparate;
    public String MapBook;
    public String MapCoordinates;
    public String MapPage;
    public String Matrix_Unique_ID;
    public String MatrixModifiedDT;
    public String MiddleSchoolName;
    public String MLS;
    public String MLSAreaMajor;
    public String MLSAreaMinor;
    public String MLSNumber;
    public String MLSNumberSaleOrLease;
    public String MoniesRequired;
    public String MonthlyPetFee;
    public String MortgageCompany;
    public String MoveInDate;
    public String MultiParcelIDYN;
    public String MultiZoningYN;
    public String MunicipalUtilityDistrictYN;
    public String NetAnnualIncome;
    public String NonRefundablePetFeeYN;
    public String NumberOfBarns;
    public String NumberOfBuildings;
    public String NumberOfDaysGuestsAllowed;
    public String NumberOfDiningAreas;
    public String NumberOfLakes;
    public String NumberOfLeaseableSpaces;
    public String NumberOfLivingAreas;
    public String NumberOfLots;
    public String NumberOfParkingSpaces;
    public String NumberOfPetsAllowed;
//    public String NumberOfPonds;
    public String NumberOfResidences;
    public String NumberOfSpacesLeased;
    public String NumberOfStallsInBarn1;
    public String NumberOfStallsInBarn2;
    public String NumberOfStallsInBarn3;
//    public String NumberOfStockTanks;
    public String NumberOfStories;
    public String NumberOfStoriesInBuilding;
    public String NumberOfUnits;
    public String NumberOfVehicles;
    public String NumberOfWaterMeters;
    public String NumberOfWells;
    public String Occupancy;
    public String OccupancyRate;
    public String OfficeSupervisor;
    public String OffMarketDate;
    public String OpenHouseCount;
    public String OpenHouseUpcoming;
    public String OriginalListPrice;
    public String OriginalMortgageDate;
    public String OtherEquipment;
    public String OwnerName;
    public String OwnerPays;
    public String OwnerPermissionToVideoYN;
    public String ParcelNumber;
    public String ParkingFeatures;
    public String ParkingSpacesCarport;
    public String ParkingSpacesCoveredTotal;
    public String ParkingSpacesGarage;
    public String PendingDate;
    public String PermitAddressInternetYN;
    public String PermitAVMYN;
    public String PermitCommentsReviewsYN;
    public String PermitInternetYN;
//    public String PetsYN;
    public String PhotoCount;
    public String PhotoModificationTimestamp;
    public String PlannedDevelopment;
    public String PoolFeatures;
    public String PoolYN;
    public String Possession;
    public String PossibleShortSaleYN;
    public String PostalCode;
    public String PostalCodePlus4;
    public String PresentUse;
    public String PriceChangeTimestamp;
    public String PrimarySchoolName;
    public String PrivateRemarks;
    public String PropertyAssociationFees;
    public String PropertySubType;
    public String PropertyType;
    public String ProposedUse;
    public String PublicRemarks;
    public String RanchName;
    public String RanchType;
    public String RATIO_ClosePrice_By_ListPrice;
    public String RATIO_ClosePrice_By_OriginalListPrice;
    public String RATIO_CurrentPrice_By_SQFT;
    public String Restrictions;
    public String RoadAssessmentYN;
    public String RoadFrontage;
    public String RoadFrontageDistance;
    public String Roof;
    public String RoomCount;
    public String SchoolDistrict;
    public String SecondMortgageYN;
    public String SecurityFeatures;
    public String SecuritySystemYN;
    public String SellerContributions;
    public String SellerType;
    public String SellingAgent_MUI;
    public String SellingAgentDirectWorkPhone;
    public String SellingAgentEmail;
    public String SellingAgentFullName;
    public String SellingAgentMLSID;
    public String SellingOffice_MUI;
    public String SellingOfficeMLSID;
    public String SellingOfficeName;
    public String SellingOfficePhone;
    public String SeniorHighSchoolName;
    public String ShowingInstructions;
    public String ShowingInstructionsType;
    public String SoilType;
    public String SoldTerms;
    public String SpecialNotes;
    public String SQFTBuilding;
    public String SQFTGross;
    public String SQFTLand;
    public String SQFTLeasable;
    public String SQFTLot;
    public String SqFtTotal;
    public String StateOrProvince;
    public String Status;
    public String StatusChangeTimestamp;
    public String StreetDirPrefix;
    public String StreetDirSuffix;
    public String StreetName;
    public String StreetNumber;
    public String StreetNumberSearchable;
    public String StreetSuffix;
    public String StructuralStyle;
    public String SubAgencyCommission;
    public String SubdividedYN;
    public String SubdivisionName;
    public String SurfaceRights;
    public String TaxLegalDescription;
    public String TempOffMarketDate;
    public String Tenancy;
    public String TenantPays;
    public String ThirdPartyAssistanceProgramYN;
    public String TitleCompanyClosing;
    public String TitleCompanyLocation;
    public String TitleCompanyPhone;
    public String TitleCompanyPreferred;
    public String Topography;
    public String TotalAnnualExpensesInclude;
    public String TransactionType;
    public String UnexemptTaxes;
    public String UnitCount;
    public String UnitNumber;
    public String URL1;
    public String URL2;
    public String URL3;
    public String URL4;
    public String URL5;
    public String Utilities;
    public String UtilitiesOther;
    public String VariableFeeYN;
    public String VirtualTourURLBranded;
    public String VirtualTourURLUnbranded;
    public String WillSubdivide;
    public String WillSubdivideYN;
    public String WithdrawnDate;
    public String WithdrawnDateSubListing;
    public String YearBuilt;
    public String YearBuiltDetails;
    public String Zoning;
    public String ZoningCommercial;

    public static String searchFields()
    {
        StringBuilder select = new StringBuilder();
        for (Field field : RetsResponse.class.getDeclaredFields())
        {
            if("MLSAreaMajor".equalsIgnoreCase(field.getName()) || "MLSAreaMinor".equalsIgnoreCase(field.getName())) {
                // these fields are not returned from api any more hence skip
                continue;
            }
            if (select.length() == 0)
            {
                select.append(field.getName());
            } else
            {
                select.append(",").append(field.getName());
            }
        }
        return select.toString();
    }

    public String address()
    {
        return addressLine1() + ", " + addressLine2();
    }

    private String addressLine2()
    {
        return City
                + ", " + StateOrProvince
                + ", " + PostalCode;
    }

    private String addressLine1()
    {
        return StreetNumber + " "
            + (StreetDirPrefix.isEmpty() ? "" : StreetDirPrefix + " ")
            + StreetName + " "
            + StreetSuffix;
    }
}
