package com.manning.bippo.dao.itf;

import java.util.Date;

/**
 * An interface shared by all Trestle property tables.
 */
public interface TrestleProperty extends AbstractProperty {

    // AbstractProperty adapter methods

    @Override
    public default Double getSqFtTotal() {
        return this.getLivingArea();
    }
    @Override
    public default Integer getNumberOfStories() {
        return this.getStories();
    }
    @Override
    public default Integer getBathsHalf() {
        return this.getBathroomsHalf();
    }
    @Override
    public default Integer getBathsFull() {
        return this.getBathroomsFull();
    }
    @Override
    public default Integer getBedsTotal() {
        return this.getBedroomsTotal();
    }
    @Override
    public default Integer getParkingSpacesCarport() {
        final Double d = this.getCarportSpaces();
        return d == null ? null : d.intValue();
    }
    @Override
    public default Integer getParkingSpacesGarage() {
        final Double d = this.getGarageSpaces();
        return d == null ? null : d.intValue();
    }
    @Override
    public default String getPoolYN() {
        final String features = this.getPoolFeatures();
        return features != null && !features.isEmpty() ? "Y" : "N";
    }
    @Override
    public default String getStatus() {
        return this.getStandardStatus();
    }

    /*
     * Most of these methods are implcitly defined in implementing classes w/
     * generated lombok @Data methods, but unfortunately we cannot rely on
     * a similar mechanism to generate this interface, so it is a bit messy.
     */

    @Override
    public boolean hasValidAddress();
    @Override
    public boolean hasStandardizableAddress();
    public String getAddressLine1();
    public String getAddressLine2();
    public Long getId();
    public int getTrestleTableOrdinal();
    public Double getAboveGradeFinishedArea();
    public void setAboveGradeFinishedArea(Double arg);
    public String getAboveGradeFinishedAreaSource();
    public void setAboveGradeFinishedAreaSource(String arg);
    public String getAboveGradeFinishedAreaUnits();
    public void setAboveGradeFinishedAreaUnits(String arg);
    public String getAccessCode();
    public void setAccessCode(String arg);
    public String getAccessibilityFeatures();
    public void setAccessibilityFeatures(String arg);
    public String getAdditionalParcelsDescription();
    public void setAdditionalParcelsDescription(String arg);
    public Boolean getAdditionalParcelsYN();
    public void setAdditionalParcelsYN(Boolean arg);
    public String getAnchorsCoTenants();
    public void setAnchorsCoTenants(String arg);
    public String getAppliances();
    public void setAppliances(String arg);
    public String getArchitecturalStyle();
    public void setArchitecturalStyle(String arg);
    public String getAssociationAmenities();
    public void setAssociationAmenities(String arg);
    public Double getAssociationFee();
    public void setAssociationFee(Double arg);
    public Double getAssociationFee2();
    public void setAssociationFee2(Double arg);
    public String getAssociationFee2Frequency();
    public void setAssociationFee2Frequency(String arg);
    public String getAssociationFeeFrequency();
    public void setAssociationFeeFrequency(String arg);
    public String getAssociationFeeIncludes();
    public void setAssociationFeeIncludes(String arg);
    public String getAssociationName();
    public void setAssociationName(String arg);
    public String getAssociationName2();
    public void setAssociationName2(String arg);
    public String getAssociationPhone();
    public void setAssociationPhone(String arg);
    public String getAssociationPhone2();
    public void setAssociationPhone2(String arg);
    public Boolean getAssociationYN();
    public void setAssociationYN(Boolean arg);
    public Boolean getAttachedGarageYN();
    public void setAttachedGarageYN(Boolean arg);
    public Date getAvailabilityDate();
    public void setAvailabilityDate(Date arg);
    public String getBasement();
    public void setBasement(String arg);
    public Boolean getBasementYN();
    public void setBasementYN(Boolean arg);
    public Integer getBathroomsFull();
    public void setBathroomsFull(Integer arg);
    public Integer getBathroomsHalf();
    public void setBathroomsHalf(Integer arg);
    public Integer getBathroomsOneQuarter();
    public void setBathroomsOneQuarter(Integer arg);
    public Integer getBathroomsPartial();
    public void setBathroomsPartial(Integer arg);
    public Integer getBathroomsThreeQuarter();
    public void setBathroomsThreeQuarter(Integer arg);
    public Integer getBathroomsTotalInteger();
    public void setBathroomsTotalInteger(Integer arg);
    public Integer getBedroomsPossible();
    public void setBedroomsPossible(Integer arg);
    public Integer getBedroomsTotal();
    public void setBedroomsTotal(Integer arg);
    public Double getBelowGradeFinishedArea();
    public void setBelowGradeFinishedArea(Double arg);
    public String getBelowGradeFinishedAreaSource();
    public void setBelowGradeFinishedAreaSource(String arg);
    public String getBelowGradeFinishedAreaUnits();
    public void setBelowGradeFinishedAreaUnits(String arg);
    public String getBodyType();
    public void setBodyType(String arg);
    public String getBuilderModel();
    public void setBuilderModel(String arg);
    public String getBuilderName();
    public void setBuilderName(String arg);
    public String getBuildingAreaSource();
    public void setBuildingAreaSource(String arg);
    public Double getBuildingAreaTotal();
    public void setBuildingAreaTotal(Double arg);
    public String getBuildingAreaUnits();
    public void setBuildingAreaUnits(String arg);
    public String getBuildingFeatures();
    public void setBuildingFeatures(String arg);
    public String getBuildingName();
    public void setBuildingName(String arg);
    public String getBusinessName();
    public void setBusinessName(String arg);
    public String getBusinessType();
    public void setBusinessType(String arg);
    public String getBuyerAgencyCompensation();
    public void setBuyerAgencyCompensation(String arg);
    public String getBuyerAgencyCompensationType();
    public void setBuyerAgencyCompensationType(String arg);
    public String getBuyerAgentAOR();
    public void setBuyerAgentAOR(String arg);
    public String getBuyerAgentDesignation();
    public void setBuyerAgentDesignation(String arg);
    public String getBuyerAgentDirectPhone();
    public void setBuyerAgentDirectPhone(String arg);
    public String getBuyerAgentEmail();
    public void setBuyerAgentEmail(String arg);
    public String getBuyerAgentFax();
    public void setBuyerAgentFax(String arg);
    public String getBuyerAgentFirstName();
    public void setBuyerAgentFirstName(String arg);
    public String getBuyerAgentFullName();
    public void setBuyerAgentFullName(String arg);
    public String getBuyerAgentHomePhone();
    public void setBuyerAgentHomePhone(String arg);
    public Integer getBuyerAgentKeyNumeric();
    public void setBuyerAgentKeyNumeric(Integer arg);
    public String getBuyerAgentLastName();
    public void setBuyerAgentLastName(String arg);
    public String getBuyerAgentMiddleName();
    public void setBuyerAgentMiddleName(String arg);
    public String getBuyerAgentMlsId();
    public void setBuyerAgentMlsId(String arg);
    public String getBuyerAgentMobilePhone();
    public void setBuyerAgentMobilePhone(String arg);
    public String getBuyerAgentNamePrefix();
    public void setBuyerAgentNamePrefix(String arg);
    public String getBuyerAgentNameSuffix();
    public void setBuyerAgentNameSuffix(String arg);
    public String getBuyerAgentOfficePhone();
    public void setBuyerAgentOfficePhone(String arg);
    public String getBuyerAgentOfficePhoneExt();
    public void setBuyerAgentOfficePhoneExt(String arg);
    public String getBuyerAgentPager();
    public void setBuyerAgentPager(String arg);
    public String getBuyerAgentPreferredPhone();
    public void setBuyerAgentPreferredPhone(String arg);
    public String getBuyerAgentPreferredPhoneExt();
    public void setBuyerAgentPreferredPhoneExt(String arg);
    public String getBuyerAgentStateLicense();
    public void setBuyerAgentStateLicense(String arg);
    public String getBuyerAgentTollFreePhone();
    public void setBuyerAgentTollFreePhone(String arg);
    public String getBuyerAgentURL();
    public void setBuyerAgentURL(String arg);
    public String getBuyerAgentVoiceMail();
    public void setBuyerAgentVoiceMail(String arg);
    public String getBuyerAgentVoiceMailExt();
    public void setBuyerAgentVoiceMailExt(String arg);
    public String getBuyerFinancing();
    public void setBuyerFinancing(String arg);
    public String getBuyerOfficeAOR();
    public void setBuyerOfficeAOR(String arg);
    public String getBuyerOfficeEmail();
    public void setBuyerOfficeEmail(String arg);
    public String getBuyerOfficeFax();
    public void setBuyerOfficeFax(String arg);
    public Integer getBuyerOfficeKeyNumeric();
    public void setBuyerOfficeKeyNumeric(Integer arg);
    public String getBuyerOfficeMlsId();
    public void setBuyerOfficeMlsId(String arg);
    public String getBuyerOfficeName();
    public void setBuyerOfficeName(String arg);
    public String getBuyerOfficePhone();
    public void setBuyerOfficePhone(String arg);
    public String getBuyerOfficePhoneExt();
    public void setBuyerOfficePhoneExt(String arg);
    public String getBuyerOfficeURL();
    public void setBuyerOfficeURL(String arg);
    public Integer getBuyerTeamKeyNumeric();
    public void setBuyerTeamKeyNumeric(Integer arg);
    public String getBuyerTeamName();
    public void setBuyerTeamName(String arg);
    public Double getCableTvExpense();
    public void setCableTvExpense(Double arg);
    public Date getCancellationDate();
    public void setCancellationDate(Date arg);
    public Double getCapRate();
    public void setCapRate(Double arg);
    public Double getCarportSpaces();
    public void setCarportSpaces(Double arg);
    public Boolean getCarportYN();
    public void setCarportYN(Boolean arg);
    public String getCarrierRoute();
    public void setCarrierRoute(String arg);
    public String getCity();
    public void setCity(String arg);
    public String getCityRegion();
    public void setCityRegion(String arg);
    public Long getCLIP();
    public void setCLIP(Long arg);
    public Date getCloseDate();
    public void setCloseDate(Date arg);
    public Double getClosePrice();
    public void setClosePrice(Double arg);
    public String getCoBuyerAgentAOR();
    public void setCoBuyerAgentAOR(String arg);
    public String getCoBuyerAgentDesignation();
    public void setCoBuyerAgentDesignation(String arg);
    public String getCoBuyerAgentDirectPhone();
    public void setCoBuyerAgentDirectPhone(String arg);
    public String getCoBuyerAgentEmail();
    public void setCoBuyerAgentEmail(String arg);
    public String getCoBuyerAgentFax();
    public void setCoBuyerAgentFax(String arg);
    public String getCoBuyerAgentFirstName();
    public void setCoBuyerAgentFirstName(String arg);
    public String getCoBuyerAgentFullName();
    public void setCoBuyerAgentFullName(String arg);
    public String getCoBuyerAgentHomePhone();
    public void setCoBuyerAgentHomePhone(String arg);
    public Integer getCoBuyerAgentKeyNumeric();
    public void setCoBuyerAgentKeyNumeric(Integer arg);
    public String getCoBuyerAgentLastName();
    public void setCoBuyerAgentLastName(String arg);
    public String getCoBuyerAgentMiddleName();
    public void setCoBuyerAgentMiddleName(String arg);
    public String getCoBuyerAgentMlsId();
    public void setCoBuyerAgentMlsId(String arg);
    public String getCoBuyerAgentMobilePhone();
    public void setCoBuyerAgentMobilePhone(String arg);
    public String getCoBuyerAgentNamePrefix();
    public void setCoBuyerAgentNamePrefix(String arg);
    public String getCoBuyerAgentNameSuffix();
    public void setCoBuyerAgentNameSuffix(String arg);
    public String getCoBuyerAgentOfficePhone();
    public void setCoBuyerAgentOfficePhone(String arg);
    public String getCoBuyerAgentOfficePhoneExt();
    public void setCoBuyerAgentOfficePhoneExt(String arg);
    public String getCoBuyerAgentPager();
    public void setCoBuyerAgentPager(String arg);
    public String getCoBuyerAgentPreferredPhone();
    public void setCoBuyerAgentPreferredPhone(String arg);
    public String getCoBuyerAgentPreferredPhoneExt();
    public void setCoBuyerAgentPreferredPhoneExt(String arg);
    public String getCoBuyerAgentStateLicense();
    public void setCoBuyerAgentStateLicense(String arg);
    public String getCoBuyerAgentTollFreePhone();
    public void setCoBuyerAgentTollFreePhone(String arg);
    public String getCoBuyerAgentURL();
    public void setCoBuyerAgentURL(String arg);
    public String getCoBuyerAgentVoiceMail();
    public void setCoBuyerAgentVoiceMail(String arg);
    public String getCoBuyerAgentVoiceMailExt();
    public void setCoBuyerAgentVoiceMailExt(String arg);
    public String getCoBuyerOfficeAOR();
    public void setCoBuyerOfficeAOR(String arg);
    public String getCoBuyerOfficeEmail();
    public void setCoBuyerOfficeEmail(String arg);
    public String getCoBuyerOfficeFax();
    public void setCoBuyerOfficeFax(String arg);
    public Integer getCoBuyerOfficeKeyNumeric();
    public void setCoBuyerOfficeKeyNumeric(Integer arg);
    public String getCoBuyerOfficeMlsId();
    public void setCoBuyerOfficeMlsId(String arg);
    public String getCoBuyerOfficeName();
    public void setCoBuyerOfficeName(String arg);
    public String getCoBuyerOfficePhone();
    public void setCoBuyerOfficePhone(String arg);
    public String getCoBuyerOfficePhoneExt();
    public void setCoBuyerOfficePhoneExt(String arg);
    public String getCoBuyerOfficeURL();
    public void setCoBuyerOfficeURL(String arg);
    public String getCoListAgentAOR();
    public void setCoListAgentAOR(String arg);
    public String getCoListAgentDesignation();
    public void setCoListAgentDesignation(String arg);
    public String getCoListAgentDirectPhone();
    public void setCoListAgentDirectPhone(String arg);
    public String getCoListAgentEmail();
    public void setCoListAgentEmail(String arg);
    public String getCoListAgentFax();
    public void setCoListAgentFax(String arg);
    public String getCoListAgentFirstName();
    public void setCoListAgentFirstName(String arg);
    public String getCoListAgentFullName();
    public void setCoListAgentFullName(String arg);
    public String getCoListAgentHomePhone();
    public void setCoListAgentHomePhone(String arg);
    public Integer getCoListAgentKeyNumeric();
    public void setCoListAgentKeyNumeric(Integer arg);
    public String getCoListAgentLastName();
    public void setCoListAgentLastName(String arg);
    public String getCoListAgentMiddleName();
    public void setCoListAgentMiddleName(String arg);
    public String getCoListAgentMlsId();
    public void setCoListAgentMlsId(String arg);
    public String getCoListAgentMobilePhone();
    public void setCoListAgentMobilePhone(String arg);
    public String getCoListAgentNamePrefix();
    public void setCoListAgentNamePrefix(String arg);
    public String getCoListAgentNameSuffix();
    public void setCoListAgentNameSuffix(String arg);
    public String getCoListAgentOfficePhone();
    public void setCoListAgentOfficePhone(String arg);
    public String getCoListAgentOfficePhoneExt();
    public void setCoListAgentOfficePhoneExt(String arg);
    public String getCoListAgentPager();
    public void setCoListAgentPager(String arg);
    public String getCoListAgentPreferredPhone();
    public void setCoListAgentPreferredPhone(String arg);
    public String getCoListAgentPreferredPhoneExt();
    public void setCoListAgentPreferredPhoneExt(String arg);
    public String getCoListAgentStateLicense();
    public void setCoListAgentStateLicense(String arg);
    public String getCoListAgentTollFreePhone();
    public void setCoListAgentTollFreePhone(String arg);
    public String getCoListAgentURL();
    public void setCoListAgentURL(String arg);
    public String getCoListAgentVoiceMail();
    public void setCoListAgentVoiceMail(String arg);
    public String getCoListAgentVoiceMailExt();
    public void setCoListAgentVoiceMailExt(String arg);
    public String getCoListOfficeAOR();
    public void setCoListOfficeAOR(String arg);
    public String getCoListOfficeEmail();
    public void setCoListOfficeEmail(String arg);
    public String getCoListOfficeFax();
    public void setCoListOfficeFax(String arg);
    public Integer getCoListOfficeKeyNumeric();
    public void setCoListOfficeKeyNumeric(Integer arg);
    public String getCoListOfficeMlsId();
    public void setCoListOfficeMlsId(String arg);
    public String getCoListOfficeName();
    public void setCoListOfficeName(String arg);
    public String getCoListOfficePhone();
    public void setCoListOfficePhone(String arg);
    public String getCoListOfficePhoneExt();
    public void setCoListOfficePhoneExt(String arg);
    public String getCoListOfficeURL();
    public void setCoListOfficeURL(String arg);
    public String getCommonInterest();
    public void setCommonInterest(String arg);
    public String getCommonWalls();
    public void setCommonWalls(String arg);
    public String getCommunityFeatures();
    public void setCommunityFeatures(String arg);
    public String getConcessions();
    public void setConcessions(String arg);
    public Integer getConcessionsAmount();
    public void setConcessionsAmount(Integer arg);
    public String getConcessionsComments();
    public void setConcessionsComments(String arg);
    public String getConstructionMaterials();
    public void setConstructionMaterials(String arg);
    public String getContinentRegion();
    public void setContinentRegion(String arg);
    public String getContingency();
    public void setContingency(String arg);
    public Date getContingentDate();
    public void setContingentDate(Date arg);
    public Date getContractStatusChangeDate();
    public void setContractStatusChangeDate(Date arg);
    public String getCooling();
    public void setCooling(String arg);
    public Boolean getCoolingYN();
    public void setCoolingYN(Boolean arg);
    public String getCopyrightNotice();
    public void setCopyrightNotice(String arg);
    public String getCountry();
    public void setCountry(String arg);
    public String getCountryRegion();
    public void setCountryRegion(String arg);
    public String getCountyOrParish();
    public void setCountyOrParish(String arg);
    public Double getCoveredSpaces();
    public void setCoveredSpaces(Double arg);
    public Boolean getCropsIncludedYN();
    public void setCropsIncludedYN(Boolean arg);
    public String getCrossStreet();
    public void setCrossStreet(String arg);
    public Double getCultivatedArea();
    public void setCultivatedArea(Double arg);
    public Integer getCumulativeDaysOnMarket();
    public void setCumulativeDaysOnMarket(Integer arg);
    public String getCurrentFinancing();
    public void setCurrentFinancing(String arg);
    public String getCurrentUse();
    public void setCurrentUse(String arg);
    public Integer getDaysOnMarket();
    public void setDaysOnMarket(Integer arg);
    public Integer getDaysOnMarketReplication();
    public void setDaysOnMarketReplication(Integer arg);
    public Date getDaysOnMarketReplicationDate();
    public void setDaysOnMarketReplicationDate(Date arg);
    public Boolean getDaysOnMarketReplicationIncreasingYN();
    public void setDaysOnMarketReplicationIncreasingYN(Boolean arg);
    public String getDevelopmentStatus();
    public void setDevelopmentStatus(String arg);
    public String getDirectionFaces();
    public void setDirectionFaces(String arg);
    public String getDirections();
    public void setDirections(String arg);
    public String getDisclaimer();
    public void setDisclaimer(String arg);
    public String getDisclosures();
    public void setDisclosures(String arg);
    public String getDistanceToBusComments();
    public void setDistanceToBusComments(String arg);
    public Integer getDistanceToBusNumeric();
    public void setDistanceToBusNumeric(Integer arg);
    public String getDistanceToBusUnits();
    public void setDistanceToBusUnits(String arg);
    public String getDistanceToElectricComments();
    public void setDistanceToElectricComments(String arg);
    public Integer getDistanceToElectricNumeric();
    public void setDistanceToElectricNumeric(Integer arg);
    public String getDistanceToElectricUnits();
    public void setDistanceToElectricUnits(String arg);
    public String getDistanceToFreewayComments();
    public void setDistanceToFreewayComments(String arg);
    public Integer getDistanceToFreewayNumeric();
    public void setDistanceToFreewayNumeric(Integer arg);
    public String getDistanceToFreewayUnits();
    public void setDistanceToFreewayUnits(String arg);
    public String getDistanceToGasComments();
    public void setDistanceToGasComments(String arg);
    public Integer getDistanceToGasNumeric();
    public void setDistanceToGasNumeric(Integer arg);
    public String getDistanceToGasUnits();
    public void setDistanceToGasUnits(String arg);
    public String getDistanceToPhoneServiceComments();
    public void setDistanceToPhoneServiceComments(String arg);
    public Integer getDistanceToPhoneServiceNumeric();
    public void setDistanceToPhoneServiceNumeric(Integer arg);
    public String getDistanceToPhoneServiceUnits();
    public void setDistanceToPhoneServiceUnits(String arg);
    public String getDistanceToPlaceofWorshipComments();
    public void setDistanceToPlaceofWorshipComments(String arg);
    public Integer getDistanceToPlaceofWorshipNumeric();
    public void setDistanceToPlaceofWorshipNumeric(Integer arg);
    public String getDistanceToPlaceofWorshipUnits();
    public void setDistanceToPlaceofWorshipUnits(String arg);
    public String getDistanceToSchoolBusComments();
    public void setDistanceToSchoolBusComments(String arg);
    public Integer getDistanceToSchoolBusNumeric();
    public void setDistanceToSchoolBusNumeric(Integer arg);
    public String getDistanceToSchoolBusUnits();
    public void setDistanceToSchoolBusUnits(String arg);
    public String getDistanceToSchoolsComments();
    public void setDistanceToSchoolsComments(String arg);
    public Integer getDistanceToSchoolsNumeric();
    public void setDistanceToSchoolsNumeric(Integer arg);
    public String getDistanceToSchoolsUnits();
    public void setDistanceToSchoolsUnits(String arg);
    public String getDistanceToSewerComments();
    public void setDistanceToSewerComments(String arg);
    public Integer getDistanceToSewerNumeric();
    public void setDistanceToSewerNumeric(Integer arg);
    public String getDistanceToSewerUnits();
    public void setDistanceToSewerUnits(String arg);
    public String getDistanceToShoppingComments();
    public void setDistanceToShoppingComments(String arg);
    public Integer getDistanceToShoppingNumeric();
    public void setDistanceToShoppingNumeric(Integer arg);
    public String getDistanceToShoppingUnits();
    public void setDistanceToShoppingUnits(String arg);
    public String getDistanceToStreetComments();
    public void setDistanceToStreetComments(String arg);
    public Integer getDistanceToStreetNumeric();
    public void setDistanceToStreetNumeric(Integer arg);
    public String getDistanceToStreetUnits();
    public void setDistanceToStreetUnits(String arg);
    public String getDistanceToWaterComments();
    public void setDistanceToWaterComments(String arg);
    public Integer getDistanceToWaterNumeric();
    public void setDistanceToWaterNumeric(Integer arg);
    public String getDistanceToWaterUnits();
    public void setDistanceToWaterUnits(String arg);
    public String getDocumentsAvailable();
    public void setDocumentsAvailable(String arg);
    public Date getDocumentsChangeTimestamp();
    public void setDocumentsChangeTimestamp(Date arg);
    public Integer getDocumentsCount();
    public void setDocumentsCount(Integer arg);
    public String getDOH1();
    public void setDOH1(String arg);
    public String getDOH2();
    public void setDOH2(String arg);
    public String getDOH3();
    public void setDOH3(String arg);
    public String getDoorFeatures();
    public void setDoorFeatures(String arg);
    public Boolean getDualVariableCompensationYN();
    public void setDualVariableCompensationYN(Boolean arg);
    public String getElectric();
    public void setElectric(String arg);
    public Double getElectricExpense();
    public void setElectricExpense(Double arg);
    public Boolean getElectricOnPropertyYN();
    public void setElectricOnPropertyYN(Boolean arg);
    public String getElementarySchool();
    public void setElementarySchool(String arg);
    public String getElementarySchoolDistrict();
    public void setElementarySchoolDistrict(String arg);
    public Integer getElevation();
    public void setElevation(Integer arg);
    public String getElevationUnits();
    public void setElevationUnits(String arg);
    public Integer getEntryLevel();
    public void setEntryLevel(Integer arg);
    public String getEntryLocation();
    public void setEntryLocation(String arg);
    public Date getEstimatedActiveDate();
    public void setEstimatedActiveDate(Date arg);
    public String getExclusions();
    public void setExclusions(String arg);
    public String getExistingLeaseType();
    public void setExistingLeaseType(String arg);
    public Date getExpirationDate();
    public void setExpirationDate(Date arg);
    public String getExteriorFeatures();
    public void setExteriorFeatures(String arg);
    public Boolean getFarmCreditServiceInclYN();
    public void setFarmCreditServiceInclYN(Boolean arg);
    public String getFarmLandAreaSource();
    public void setFarmLandAreaSource(String arg);
    public String getFarmLandAreaUnits();
    public void setFarmLandAreaUnits(String arg);
    public String getFencing();
    public void setFencing(String arg);
    public String getFinancialDataSource();
    public void setFinancialDataSource(String arg);
    public String getFireplaceFeatures();
    public void setFireplaceFeatures(String arg);
    public Integer getFireplacesTotal();
    public void setFireplacesTotal(Integer arg);
    public Boolean getFireplaceYN();
    public void setFireplaceYN(Boolean arg);
    public String getFlooring();
    public void setFlooring(String arg);
    public Double getFoundationArea();
    public void setFoundationArea(Double arg);
    public String getFoundationDetails();
    public void setFoundationDetails(String arg);
    public String getFrontageLength();
    public void setFrontageLength(String arg);
    public String getFrontageType();
    public void setFrontageType(String arg);
    public Double getFuelExpense();
    public void setFuelExpense(Double arg);
    public String getFurnished();
    public void setFurnished(String arg);
    public Double getFurnitureReplacementExpense();
    public void setFurnitureReplacementExpense(Double arg);
    public Double getGarageSpaces();
    public void setGarageSpaces(Double arg);
    public Boolean getGarageYN();
    public void setGarageYN(Boolean arg);
    public Double getGardenerExpense();
    public void setGardenerExpense(Double arg);
    public Boolean getGrazingPermitsBlmYN();
    public void setGrazingPermitsBlmYN(Boolean arg);
    public Boolean getGrazingPermitsForestServiceYN();
    public void setGrazingPermitsForestServiceYN(Boolean arg);
    public Boolean getGrazingPermitsPrivateYN();
    public void setGrazingPermitsPrivateYN(Boolean arg);
    public String getGreenEnergyEfficient();
    public void setGreenEnergyEfficient(String arg);
    public String getGreenEnergyGeneration();
    public void setGreenEnergyGeneration(String arg);
    public String getGreenIndoorAirQuality();
    public void setGreenIndoorAirQuality(String arg);
    public String getGreenLocation();
    public void setGreenLocation(String arg);
    public String getGreenSustainability();
    public void setGreenSustainability(String arg);
    public String getGreenWaterConservation();
    public void setGreenWaterConservation(String arg);
    public Double getGrossIncome();
    public void setGrossIncome(Double arg);
    public Double getGrossScheduledIncome();
    public void setGrossScheduledIncome(Double arg);
    public Boolean getHabitableResidenceYN();
    public void setHabitableResidenceYN(Boolean arg);
    public String getHeating();
    public void setHeating(String arg);
    public Boolean getHeatingYN();
    public void setHeatingYN(Boolean arg);
    public String getHighSchool();
    public void setHighSchool(String arg);
    public String getHighSchoolDistrict();
    public void setHighSchoolDistrict(String arg);
    public Boolean getHomeWarrantyYN();
    public void setHomeWarrantyYN(Boolean arg);
    public String getHorseAmenities();
    public void setHorseAmenities(String arg);
    public Boolean getHorseYN();
    public void setHorseYN(Boolean arg);
    public String getHoursDaysOfOperation();
    public void setHoursDaysOfOperation(String arg);
    public String getHoursDaysOfOperationDescription();
    public void setHoursDaysOfOperationDescription(String arg);
    public String getInclusions();
    public void setInclusions(String arg);
    public String getIncomeIncludes();
    public void setIncomeIncludes(String arg);
    public Double getInsuranceExpense();
    public void setInsuranceExpense(Double arg);
    public String getInteriorFeatures();
    public void setInteriorFeatures(String arg);
    public Boolean getInternetAddressDisplayYN();
    public void setInternetAddressDisplayYN(Boolean arg);
    public Boolean getInternetAutomatedValuationDisplayYN();
    public void setInternetAutomatedValuationDisplayYN(Boolean arg);
    public Boolean getInternetConsumerCommentYN();
    public void setInternetConsumerCommentYN(Boolean arg);
    public Boolean getInternetEntireListingDisplayYN();
    public void setInternetEntireListingDisplayYN(Boolean arg);
    public String getIrrigationSource();
    public void setIrrigationSource(String arg);
    public Double getIrrigationWaterRightsAcres();
    public void setIrrigationWaterRightsAcres(Double arg);
    public Boolean getIrrigationWaterRightsYN();
    public void setIrrigationWaterRightsYN(Boolean arg);
    public String getLaborInformation();
    public void setLaborInformation(String arg);
    public Double getLandLeaseAmount();
    public void setLandLeaseAmount(Double arg);
    public String getLandLeaseAmountFrequency();
    public void setLandLeaseAmountFrequency(String arg);
    public Date getLandLeaseExpirationDate();
    public void setLandLeaseExpirationDate(Date arg);
    public Boolean getLandLeaseYN();
    public void setLandLeaseYN(Boolean arg);
    public Double getLatitude();
    public void setLatitude(Double arg);
    public String getLaundryFeatures();
    public void setLaundryFeatures(String arg);
    public Double getLeasableArea();
    public void setLeasableArea(Double arg);
    public String getLeasableAreaUnits();
    public void setLeasableAreaUnits(String arg);
    public Double getLeaseAmount();
    public void setLeaseAmount(Double arg);
    public String getLeaseAmountFrequency();
    public void setLeaseAmountFrequency(String arg);
    public Boolean getLeaseAssignableYN();
    public void setLeaseAssignableYN(Boolean arg);
    public Boolean getLeaseConsideredYN();
    public void setLeaseConsideredYN(Boolean arg);
    public Date getLeaseExpiration();
    public void setLeaseExpiration(Date arg);
    public String getLeaseRenewalCompensation();
    public void setLeaseRenewalCompensation(String arg);
    public Boolean getLeaseRenewalOptionYN();
    public void setLeaseRenewalOptionYN(Boolean arg);
    public String getLeaseTerm();
    public void setLeaseTerm(String arg);
    public String getLevels();
    public void setLevels(String arg);
    public String getLicense1();
    public void setLicense1(String arg);
    public String getLicense2();
    public void setLicense2(String arg);
    public String getLicense3();
    public void setLicense3(String arg);
    public Double getLicensesExpense();
    public void setLicensesExpense(Double arg);
    public String getListAgentAOR();
    public void setListAgentAOR(String arg);
    public String getListAgentDesignation();
    public void setListAgentDesignation(String arg);
    public String getListAgentDirectPhone();
    public void setListAgentDirectPhone(String arg);
    public String getListAgentEmail();
    public void setListAgentEmail(String arg);
    public String getListAgentFax();
    public void setListAgentFax(String arg);
    public String getListAgentFirstName();
    public void setListAgentFirstName(String arg);
    public String getListAgentFullName();
    public void setListAgentFullName(String arg);
    public String getListAgentHomePhone();
    public void setListAgentHomePhone(String arg);
    public Integer getListAgentKeyNumeric();
    public void setListAgentKeyNumeric(Integer arg);
    public String getListAgentLastName();
    public void setListAgentLastName(String arg);
    public String getListAgentMiddleName();
    public void setListAgentMiddleName(String arg);
    public String getListAgentMlsId();
    public void setListAgentMlsId(String arg);
    public String getListAgentMobilePhone();
    public void setListAgentMobilePhone(String arg);
    public String getListAgentNamePrefix();
    public void setListAgentNamePrefix(String arg);
    public String getListAgentNameSuffix();
    public void setListAgentNameSuffix(String arg);
    public String getListAgentOfficePhone();
    public void setListAgentOfficePhone(String arg);
    public String getListAgentOfficePhoneExt();
    public void setListAgentOfficePhoneExt(String arg);
    public String getListAgentPager();
    public void setListAgentPager(String arg);
    public String getListAgentPreferredPhone();
    public void setListAgentPreferredPhone(String arg);
    public String getListAgentPreferredPhoneExt();
    public void setListAgentPreferredPhoneExt(String arg);
    public String getListAgentStateLicense();
    public void setListAgentStateLicense(String arg);
    public String getListAgentTollFreePhone();
    public void setListAgentTollFreePhone(String arg);
    public String getListAgentURL();
    public void setListAgentURL(String arg);
    public String getListAgentVoiceMail();
    public void setListAgentVoiceMail(String arg);
    public String getListAgentVoiceMailExt();
    public void setListAgentVoiceMailExt(String arg);
    public String getListAOR();
    public void setListAOR(String arg);
    public String getListingAgreement();
    public void setListingAgreement(String arg);
    public Date getListingContractDate();
    public void setListingContractDate(Date arg);
    public String getListingId();
    public void setListingId(String arg);
    public String getListingKey();
    public void setListingKey(String arg);
    public Integer getListingKeyNumeric();
    public void setListingKeyNumeric(Integer arg);
    public String getListingService();
    public void setListingService(String arg);
    public String getListingTerms();
    public void setListingTerms(String arg);
    public String getListOfficeAOR();
    public void setListOfficeAOR(String arg);
    public String getListOfficeEmail();
    public void setListOfficeEmail(String arg);
    public String getListOfficeFax();
    public void setListOfficeFax(String arg);
    public Integer getListOfficeKeyNumeric();
    public void setListOfficeKeyNumeric(Integer arg);
    public String getListOfficeMlsId();
    public void setListOfficeMlsId(String arg);
    public String getListOfficeName();
    public void setListOfficeName(String arg);
    public String getListOfficePhone();
    public void setListOfficePhone(String arg);
    public String getListOfficePhoneExt();
    public void setListOfficePhoneExt(String arg);
    public String getListOfficeURL();
    public void setListOfficeURL(String arg);
    public Double getListPrice();
    public void setListPrice(Double arg);
    public Double getListPriceLow();
    public void setListPriceLow(Double arg);
    public Integer getListTeamKeyNumeric();
    public void setListTeamKeyNumeric(Integer arg);
    public String getListTeamName();
    public void setListTeamName(String arg);
    public Double getLivingArea();
    public void setLivingArea(Double arg);
    public String getLivingAreaSource();
    public void setLivingAreaSource(String arg);
    public String getLivingAreaUnits();
    public void setLivingAreaUnits(String arg);
    public String getLockBoxLocation();
    public void setLockBoxLocation(String arg);
    public String getLockBoxSerialNumber();
    public void setLockBoxSerialNumber(String arg);
    public String getLockBoxType();
    public void setLockBoxType(String arg);
    public Double getLongitude();
    public void setLongitude(Double arg);
    public String getLotDimensionsSource();
    public void setLotDimensionsSource(String arg);
    public String getLotFeatures();
    public void setLotFeatures(String arg);
    public Double getLotSizeAcres();
    public void setLotSizeAcres(Double arg);
    public Double getLotSizeArea();
    public void setLotSizeArea(Double arg);
    public String getLotSizeDimensions();
    public void setLotSizeDimensions(String arg);
    public String getLotSizeSource();
    public void setLotSizeSource(String arg);
    public Double getLotSizeSquareFeet();
    public void setLotSizeSquareFeet(Double arg);
    public String getLotSizeUnits();
    public void setLotSizeUnits(String arg);
    public Integer getMainLevelBathrooms();
    public void setMainLevelBathrooms(Integer arg);
    public Integer getMainLevelBedrooms();
    public void setMainLevelBedrooms(Integer arg);
    public Double getMaintenanceExpense();
    public void setMaintenanceExpense(Double arg);
    public Date getMajorChangeTimestamp();
    public void setMajorChangeTimestamp(Date arg);
    public String getMajorChangeType();
    public void setMajorChangeType(String arg);
    public String getMake();
    public void setMake(String arg);
    public Double getManagerExpense();
    public void setManagerExpense(Double arg);
    public String getMapCoordinate();
    public void setMapCoordinate(String arg);
    public String getMapCoordinateSource();
    public void setMapCoordinateSource(String arg);
    public String getMapURL();
    public void setMapURL(String arg);
    public String getMiddleOrJuniorSchool();
    public void setMiddleOrJuniorSchool(String arg);
    public String getMiddleOrJuniorSchoolDistrict();
    public void setMiddleOrJuniorSchoolDistrict(String arg);
    public String getMLSAreaMajor();
    public void setMLSAreaMajor(String arg);
    public String getMLSAreaMinor();
    public void setMLSAreaMinor(String arg);
    public String getMlsStatus();
    public void setMlsStatus(String arg);
    public String getMobileDimUnits();
    public void setMobileDimUnits(String arg);
    public Boolean getMobileHomeRemainsYN();
    public void setMobileHomeRemainsYN(Boolean arg);
    public Integer getMobileLength();
    public void setMobileLength(Integer arg);
    public Integer getMobileWidth();
    public void setMobileWidth(Integer arg);
    public String getModel();
    public void setModel(String arg);
    public Date getModificationTimestamp();
    public void setModificationTimestamp(Date arg);
    public Double getNetOperatingIncome();
    public void setNetOperatingIncome(Double arg);
    public Boolean getNewConstructionYN();
    public void setNewConstructionYN(Boolean arg);
    public Double getNewTaxesExpense();
    public void setNewTaxesExpense(Double arg);
    public Integer getNumberOfBuildings();
    public void setNumberOfBuildings(Integer arg);
    public Integer getNumberOfFullTimeEmployees();
    public void setNumberOfFullTimeEmployees(Integer arg);
    public Integer getNumberOfLots();
    public void setNumberOfLots(Integer arg);
    public Integer getNumberOfPads();
    public void setNumberOfPads(Integer arg);
    public Integer getNumberOfPartTimeEmployees();
    public void setNumberOfPartTimeEmployees(Integer arg);
    public Integer getNumberOfSeparateElectricMeters();
    public void setNumberOfSeparateElectricMeters(Integer arg);
    public Integer getNumberOfSeparateGasMeters();
    public void setNumberOfSeparateGasMeters(Integer arg);
    public Integer getNumberOfSeparateWaterMeters();
    public void setNumberOfSeparateWaterMeters(Integer arg);
    public Integer getNumberOfUnitsInCommunity();
    public void setNumberOfUnitsInCommunity(Integer arg);
    public Integer getNumberOfUnitsLeased();
    public void setNumberOfUnitsLeased(Integer arg);
    public Integer getNumberOfUnitsMoMo();
    public void setNumberOfUnitsMoMo(Integer arg);
    public Integer getNumberOfUnitsTotal();
    public void setNumberOfUnitsTotal(Integer arg);
    public Integer getNumberOfUnitsVacant();
    public void setNumberOfUnitsVacant(Integer arg);
    public String getOccupantName();
    public void setOccupantName(String arg);
    public String getOccupantPhone();
    public void setOccupantPhone(String arg);
    public String getOccupantType();
    public void setOccupantType(String arg);
    public Date getOffMarketDate();
    public void setOffMarketDate(Date arg);
    public Date getOffMarketTimestamp();
    public void setOffMarketTimestamp(Date arg);
    public Date getOnMarketDate();
    public void setOnMarketDate(Date arg);
    public Date getOnMarketTimestamp();
    public void setOnMarketTimestamp(Date arg);
    public Double getOpenParkingSpaces();
    public void setOpenParkingSpaces(Double arg);
    public Boolean getOpenParkingYN();
    public void setOpenParkingYN(Boolean arg);
    public Double getOperatingExpense();
    public void setOperatingExpense(Double arg);
    public String getOperatingExpenseIncludes();
    public void setOperatingExpenseIncludes(String arg);
    public Date getOriginalEntryTimestamp();
    public void setOriginalEntryTimestamp(Date arg);
    public Double getOriginalListPrice();
    public void setOriginalListPrice(Double arg);
    public String getOriginatingSystemID();
    public void setOriginatingSystemID(String arg);
    public String getOriginatingSystemKey();
    public void setOriginatingSystemKey(String arg);
    public String getOriginatingSystemName();
    public void setOriginatingSystemName(String arg);
    public String getOriginatingSystemSubName();
    public void setOriginatingSystemSubName(String arg);
    public String getOtherEquipment();
    public void setOtherEquipment(String arg);
    public Double getOtherExpense();
    public void setOtherExpense(Double arg);
    public String getOtherParking();
    public void setOtherParking(String arg);
    public String getOtherStructures();
    public void setOtherStructures(String arg);
    public String getOwnerName();
    public void setOwnerName(String arg);
    public String getOwnerPays();
    public void setOwnerPays(String arg);
    public String getOwnerPhone();
    public void setOwnerPhone(String arg);
    public String getOwnership();
    public void setOwnership(String arg);
    public String getOwnershipType();
    public void setOwnershipType(String arg);
    public String getParcelNumber();
    public void setParcelNumber(String arg);
    public String getParkingFeatures();
    public void setParkingFeatures(String arg);
    public Double getParkingTotal();
    public void setParkingTotal(Double arg);
    public String getParkManagerName();
    public void setParkManagerName(String arg);
    public String getParkManagerPhone();
    public void setParkManagerPhone(String arg);
    public String getParkName();
    public void setParkName(String arg);
    public Double getPastureArea();
    public void setPastureArea(Double arg);
    public String getPatioAndPorchFeatures();
    public void setPatioAndPorchFeatures(String arg);
    public Date getPendingTimestamp();
    public void setPendingTimestamp(Date arg);
    public String getPermission();
    public void setPermission(String arg);
    public String getPermissionPrivate();
    public void setPermissionPrivate(String arg);
    public Double getPestControlExpense();
    public void setPestControlExpense(Double arg);
    public String getPetsAllowed();
    public void setPetsAllowed(String arg);
    public Date getPhotosChangeTimestamp();
    public void setPhotosChangeTimestamp(Date arg);
    public Integer getPhotosCount();
    public void setPhotosCount(Integer arg);
    public Double getPoolExpense();
    public void setPoolExpense(Double arg);
    public String getPoolFeatures();
    public void setPoolFeatures(String arg);
    public Boolean getPoolPrivateYN();
    public void setPoolPrivateYN(Boolean arg);
    public String getPossession();
    public void setPossession(String arg);
    public String getPossibleUse();
    public void setPossibleUse(String arg);
    public String getPostalCity();
    public void setPostalCity(String arg);
    public String getPostalCode();
    public void setPostalCode(String arg);
    public String getPostalCodePlus4();
    public void setPostalCodePlus4(String arg);
    public Double getPreviousListPrice();
    public void setPreviousListPrice(Double arg);
    public Date getPriceChangeTimestamp();
    public void setPriceChangeTimestamp(Date arg);
    public String getPrivateOfficeRemarks();
    public void setPrivateOfficeRemarks(String arg);
    public String getPrivateRemarks();
    public void setPrivateRemarks(String arg);
    public Double getProfessionalManagementExpense();
    public void setProfessionalManagementExpense(Double arg);
    public Boolean getPropertyAttachedYN();
    public void setPropertyAttachedYN(Boolean arg);
    public String getPropertyCondition();
    public void setPropertyCondition(String arg);
    public String getPropertySubType();
    public void setPropertySubType(String arg);
    public String getPropertyType();
    public void setPropertyType(String arg);
    public String getPublicRemarks();
    public void setPublicRemarks(String arg);
    public String getPublicSurveyRange();
    public void setPublicSurveyRange(String arg);
    public String getPublicSurveySection();
    public void setPublicSurveySection(String arg);
    public String getPublicSurveyTownship();
    public void setPublicSurveyTownship(String arg);
    public Date getPurchaseContractDate();
    public void setPurchaseContractDate(Date arg);
    public Double getRangeArea();
    public void setRangeArea(Double arg);
    public Boolean getRentControlYN();
    public void setRentControlYN(Boolean arg);
    public String getRentIncludes();
    public void setRentIncludes(String arg);
    public String getRoadFrontageType();
    public void setRoadFrontageType(String arg);
    public String getRoadResponsibility();
    public void setRoadResponsibility(String arg);
    public String getRoadSurfaceType();
    public void setRoadSurfaceType(String arg);
    public String getRoof();
    public void setRoof(String arg);
    public Integer getRoomsTotal();
    public void setRoomsTotal(Integer arg);
    public String getRVParkingDimensions();
    public void setRVParkingDimensions(String arg);
    public Integer getSeatingCapacity();
    public void setSeatingCapacity(Integer arg);
    public String getSecurityFeatures();
    public void setSecurityFeatures(String arg);
    public Boolean getSeniorCommunityYN();
    public void setSeniorCommunityYN(Boolean arg);
    public String getSerialU();
    public void setSerialU(String arg);
    public String getSerialX();
    public void setSerialX(String arg);
    public String getSerialXX();
    public void setSerialXX(String arg);
    public String getSewer();
    public void setSewer(String arg);
    public Integer getShowingAdvanceNotice();
    public void setShowingAdvanceNotice(Integer arg);
    public Boolean getShowingAttendedYN();
    public void setShowingAttendedYN(Boolean arg);
    public String getShowingContactName();
    public void setShowingContactName(String arg);
    public String getShowingContactPhone();
    public void setShowingContactPhone(String arg);
    public String getShowingContactPhoneExt();
    public void setShowingContactPhoneExt(String arg);
    public String getShowingContactType();
    public void setShowingContactType(String arg);
    public String getShowingDays();
    public void setShowingDays(String arg);
    public Date getShowingEndTime();
    public void setShowingEndTime(Date arg);
    public String getShowingInstructions();
    public void setShowingInstructions(String arg);
    public String getShowingRequirements();
    public void setShowingRequirements(String arg);
    public Date getShowingStartTime();
    public void setShowingStartTime(Date arg);
    public Boolean getSignOnPropertyYN();
    public void setSignOnPropertyYN(Boolean arg);
    public String getSkirt();
    public void setSkirt(String arg);
    public String getSourceSystemID();
    public void setSourceSystemID(String arg);
    public String getSourceSystemKey();
    public void setSourceSystemKey(String arg);
    public String getSourceSystemName();
    public void setSourceSystemName(String arg);
    public String getSpaFeatures();
    public void setSpaFeatures(String arg);
    public Boolean getSpaYN();
    public void setSpaYN(Boolean arg);
    public String getSpecialLicenses();
    public void setSpecialLicenses(String arg);
    public String getSpecialListingConditions();
    public void setSpecialListingConditions(String arg);
    public String getStandardStatus();
    public void setStandardStatus(String arg);
    public String getStateOrProvince();
    public void setStateOrProvince(String arg);
    public String getStateRegion();
    public void setStateRegion(String arg);
    public Date getStatusChangeTimestamp();
    public void setStatusChangeTimestamp(Date arg);
    public Integer getStories();
    public void setStories(Integer arg);
    public Integer getStoriesTotal();
    public void setStoriesTotal(Integer arg);
    public String getStreetAdditionalInfo();
    public void setStreetAdditionalInfo(String arg);
    public String getStreetDirPrefix();
    public void setStreetDirPrefix(String arg);
    public String getStreetDirSuffix();
    public void setStreetDirSuffix(String arg);
    public String getStreetName();
    public void setStreetName(String arg);
    public String getStreetNumber();
    public void setStreetNumber(String arg);
    public Integer getStreetNumberNumeric();
    public void setStreetNumberNumeric(Integer arg);
    public String getStreetSuffix();
    public void setStreetSuffix(String arg);
    public String getStreetSuffixModifier();
    public void setStreetSuffixModifier(String arg);
    public String getStructureType();
    public void setStructureType(String arg);
    public String getSubAgencyCompensation();
    public void setSubAgencyCompensation(String arg);
    public String getSubAgencyCompensationType();
    public void setSubAgencyCompensationType(String arg);
    public String getSubdivisionName();
    public void setSubdivisionName(String arg);
    public Double getSuppliesExpense();
    public void setSuppliesExpense(Double arg);
    public String getSyndicateTo();
    public void setSyndicateTo(String arg);
    public String getSyndicationRemarks();
    public void setSyndicationRemarks(String arg);
    public Double getTaxAnnualAmount();
    public void setTaxAnnualAmount(Double arg);
    public Integer getTaxAssessedValue();
    public void setTaxAssessedValue(Integer arg);
    public String getTaxBlock();
    public void setTaxBlock(String arg);
    public String getTaxBookNumber();
    public void setTaxBookNumber(String arg);
    public String getTaxLegalDescription();
    public void setTaxLegalDescription(String arg);
    public String getTaxLot();
    public void setTaxLot(String arg);
    public String getTaxMapNumber();
    public void setTaxMapNumber(String arg);
    public Double getTaxOtherAnnualAssessmentAmount();
    public void setTaxOtherAnnualAssessmentAmount(Double arg);
    public String getTaxParcelLetter();
    public void setTaxParcelLetter(String arg);
    public String getTaxStatusCurrent();
    public void setTaxStatusCurrent(String arg);
    public String getTaxTract();
    public void setTaxTract(String arg);
    public Integer getTaxYear();
    public void setTaxYear(Integer arg);
    public String getTenantPays();
    public void setTenantPays(String arg);
    public String getTopography();
    public void setTopography(String arg);
    public Double getTotalActualRent();
    public void setTotalActualRent(Double arg);
    public String getTownship();
    public void setTownship(String arg);
    public String getTransactionBrokerCompensation();
    public void setTransactionBrokerCompensation(String arg);
    public String getTransactionBrokerCompensationType();
    public void setTransactionBrokerCompensationType(String arg);
    public Double getTrashExpense();
    public void setTrashExpense(Double arg);
    public String getUnitNumber();
    public void setUnitNumber(String arg);
    public String getUnitsFurnished();
    public void setUnitsFurnished(String arg);
    public String getUniversalPropertyId();
    public void setUniversalPropertyId(String arg);
    public String getUniversalPropertySubId();
    public void setUniversalPropertySubId(String arg);
    public String getUnparsedAddress();
    public void setUnparsedAddress(String arg);
    public String getUtilities();
    public void setUtilities(String arg);
    public Integer getVacancyAllowance();
    public void setVacancyAllowance(Integer arg);
    public Double getVacancyAllowanceRate();
    public void setVacancyAllowanceRate(Double arg);
    public String getVegetation();
    public void setVegetation(String arg);
    public Date getVideosChangeTimestamp();
    public void setVideosChangeTimestamp(Date arg);
    public Integer getVideosCount();
    public void setVideosCount(Integer arg);
    public String getView();
    public void setView(String arg);
    public Boolean getViewYN();
    public void setViewYN(Boolean arg);
    public String getVirtualTourURLBranded();
    public void setVirtualTourURLBranded(String arg);
    public String getVirtualTourURLUnbranded();
    public void setVirtualTourURLUnbranded(String arg);
    public Integer getWalkScore();
    public void setWalkScore(Integer arg);
    public String getWaterBodyName();
    public void setWaterBodyName(String arg);
    public String getWaterfrontFeatures();
    public void setWaterfrontFeatures(String arg);
    public Boolean getWaterfrontYN();
    public void setWaterfrontYN(Boolean arg);
    public Double getWaterSewerExpense();
    public void setWaterSewerExpense(Double arg);
    public String getWaterSource();
    public void setWaterSource(String arg);
    public String getWindowFeatures();
    public void setWindowFeatures(String arg);
    public Date getWithdrawnDate();
    public void setWithdrawnDate(Date arg);
    public Double getWoodedArea();
    public void setWoodedArea(Double arg);
    public Double getWorkmansCompensationExpense();
    public void setWorkmansCompensationExpense(Double arg);
    public Double getX_LocationLatitude();
    public void setX_LocationLatitude(Double arg);
    public Double getX_LocationLongitude();
    public void setX_LocationLongitude(Double arg);
    public String getX_GeocodeSource();
    public void setX_GeocodeSource(String arg);
    public String getX_LandTenure();
    public void setX_LandTenure(String arg);
    public String getX_LivingAreaRange();
    public void setX_LivingAreaRange(String arg);
    public Integer getYearBuilt();
    public void setYearBuilt(Integer arg);
    public String getYearBuiltDetails();
    public void setYearBuiltDetails(String arg);
    public Integer getYearBuiltEffective();
    public void setYearBuiltEffective(Integer arg);
    public String getYearBuiltSource();
    public void setYearBuiltSource(String arg);
    public Integer getYearEstablished();
    public void setYearEstablished(Integer arg);
    public Integer getYearsCurrentOwner();
    public void setYearsCurrentOwner(Integer arg);
    public String getZoning();
    public void setZoning(String arg);
    public String getZoningDescription();
    public void setZoningDescription(String arg);
}
